GET http://localhost:3000/setup HTTP/1.1
###

POST http://localhost:3000/crewName HTTP/1.1
Content-Type: application/json

{
    "name":"Harrison Ford",
    "type": "Actor"
}
###

POST http://localhost:3000/crew HTTP/1.1
Content-Type: application/json

{
    "name":"John Rhys-Davies",
    "type": "Actor"
}
###

GET http://localhost:3000/actors HTTP/1.1
###

GET http://localhost:3000/crew HTTP/1.1
###

GET http://localhost:3000/directors HTTP/1.1
###

GET http://localhost:3000/emails HTTP/1.1
###

POST  http://localhost:3000/movies HTTP/1.1
Content-Type: application/json

{
  "movies":[
    {
      "Title":"The Temple of Doom",
      "Description":"After arriving in India, Indiana Jones is asked by a desperate village to find a mystical stone. He agrees – and stumbles upon a secret cult plotting a terrible plan in the catacombs of an ancient palace.",
      "ReleaseDate":"23/05/1984",
      "Crew":[
        {
            "Id":"625ecf977726d02af8756041",
            "Name":"Steven Spielberg",
            "Type": "Director"
        },
        {
            "Id":"625ecf977726d02af8756037",
            "Name":"Harrison Ford",
            "Type": "Actor"
        }
      ]
    },
    {
      "Title":"American Graffiti",
      "Description":"A couple of high school graduates spend one final night cruising the strip with their buddies before they go off to college.",
      "ReleaseDate":"11/08/1973",
      "Crew":[
        {
            "Id":"625ecf977726d02af875603e",
            "Name":"George Lucas",
            "Type": "Director"
        },
        {
            "Id":"625ecf977726d02af8756037",
            "Name":"Harrison Ford",
            "Type": "Actor"
        }
      ]
    }
    ]
}
###

GET http://localhost:3000/movie/625ecf987726d02af8756047 HTTP/1.1
###

GET http://localhost:3000/movies HTTP/1.1
###

GET http://localhost:3000/sendmail HTTP/1.1
###

POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "username": "Djenghis",
  "email": "Carmino.deschuijmere@outlook.com",
  "password": "Howestisthebest",
  "movies": [],
  "crew": []
}
###

POST http://localhost:3000/user/62630296b03d2df707d1a2f9 HTTP/1.1
Content-Type: application/json

{
    "id": "",
    "title": ""
}
###

POST  http://localhost:3000/user/62630296b03d2df707d1a2f9/login HTTP/1.1
Content-Type: application/json

{
    "email": "carmino.deschuijmere@outlook.com",
    "password": "Howestiszekerthebest"
}
###

# POST  http://localhost:3000/user/62630296b03d2df707d1a2f9/password HTTP/1.1
# Content-Type: application/json
# {
#     "password": "Howestiszekerthebest"
# }
###

GET http://localhost:3000/user/62630296b03d2df707d1a2f9 HTTP/1.1
###

GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjYzMDI5NmIwM2QyZGY3MDdkMWEyZjkiLCJnaXZlbl9uYW1lIjoiQ2FybWlubyIsIm5iZiI6MTY1MDk3MzgwNCwiZXhwIjoxNjUwOTc3NDA0LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwIiwiYXVkIjoibW92aWVfYXBpX3VzZXJzIn0.hlBtpdpt8edKzdVaeABiJT_sKJgcfsaaNblRdbL1OC4
###

DELETE http://localhost:3000/user/62630296b03d2df707d1a2f9/crew/625ecf977726d02af875603d HTTP/1.1
Content-Type: application/json

###

DELETE  http://localhost:3000/user/62630296b03d2df707d1a2f9/movie/625ecf987726d02af8756043 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "Carmino",
    "password": "Howestisthebest"
}
###